// TODO: Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');

// TODO: Create an array of questions for user input
const questions = [
    {
        type: 'list',
        name: 'options',
        message: 'What would you like to do?',
        choices: ['View All Departments', 'View All Roles', 'View All Employees', 'Add Department', 'Add Role', 'Add Employee', 'Update Employee Role'],
        validate: nameInput => {
          if (nameInput) {
            return true;
          } else {
            console.log('Choose an option');
            return false;
          }
        }
    },
];

// TODO: Create functions to link choice to tables

function init() {inquirer.prompt(questions).then(response => {
    // call write file and pass the answers generated by the markdown function
    writeToFile("./dist/README.md", generateMarkdown(response))
}

)}